server:
  port: 8000

spring:
  application:
    name: scrabble-calculator

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect